Repository imssein/VEGIN, pull requests merged in 2022-09, with the labels that each got.

#66 feat: api 포맷 변경
  backend/src/main/java/com/project/vegan/domain/diet/controller/DietController.java
  backend/src/main/java/com/project/vegan/domain/diet/response/DietDto.java
  backend/src/main/java/com/project/vegan/domain/post/response/DetailPostDto.java
  backend/src/main/java/com/project/vegan/domain/post/response/SimplePostDto.java
  backend/src/main/java/com/project/vegan/domain/review/response/ReviewDto.java
  backend/src/main/java/com/project/vegan/domain/store/response/StoreDetailDto.java
  backend/src/main/java/com/project/vegan/domain/store/response/StoreDto.java
Labels: ✨ Feature

#67 feat: 관심목록 api 구현
  backend/src/main/java/com/project/vegan/domain/like/controller/LikeController.java
  backend/src/main/java/com/project/vegan/domain/like/repository/LikeRepository.java
  backend/src/main/java/com/project/vegan/domain/like/repository/LikeRepositoryCustom.java
  backend/src/main/java/com/project/vegan/domain/like/repository/LikeRepositoryImpl.java
  backend/src/main/java/com/project/vegan/domain/like/response/LikePostDto.java
  backend/src/main/java/com/project/vegan/domain/like/response/LikeStoreDto.java
  backend/src/main/java/com/project/vegan/domain/like/service/LikeService.java
  backend/src/main/java/com/project/vegan/domain/post/controller/PostController.java
Labels: ✨ Feature

#68 feat: 게시글(채식피드) 해시태그 검색 기능 추가
  backend/src/main/java/com/project/vegan/domain/post/controller/PostController.java
  backend/src/main/java/com/project/vegan/domain/post/repository/PostRepositoryCustom.java
  backend/src/main/java/com/project/vegan/domain/post/repository/PostRepositoryImpl.java
  backend/src/main/java/com/project/vegan/domain/post/service/PostService.java
  backend/src/main/java/com/project/vegan/domain/store/repository/StoreRepositoryCustom.java
  backend/src/main/java/com/project/vegan/domain/store/repository/StoreRepositoryImpl.java
Labels: ✨ Feature

#69 feat: 게시글 관련 API 연동
  frontend/components/feed/CommentForm.jsx
  frontend/components/feed/EditForm.jsx
  frontend/components/feed/Feed.jsx
  frontend/components/feed/FeedForm.jsx
  frontend/components/feed/MoreFeature.jsx
  frontend/components/feed/containers/FeedListContainer.jsx
  frontend/components/feed/containers/ReviewListContainer.jsx
  frontend/components/post/CommentForm.jsx
  frontend/components/post/FeedForm.jsx
  frontend/components/post/PostCard.jsx
  frontend/components/post/PostCardButton.jsx
  frontend/components/post/PostCardContent.jsx
  frontend/components/post/PostFormLogo.jsx
  frontend/components/post/PostImages.jsx
  frontend/pages/editFeed/[[...params]].js
  frontend/pages/feedPage.js
  frontend/pages/writeFeed.js
  frontend/pages/writePost.js
  frontend/services/post.service.js
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#70 feat: 식당 리뷰 구현
  frontend/components/review/EditForm.jsx
  frontend/components/review/MoreFeature.jsx
  frontend/components/review/Review.jsx
  frontend/components/review/Reviewform.jsx
  frontend/pages/editReview/[[...params]].js
  frontend/pages/writeReview/[[...params]].js
  frontend/services/review.service.js
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#71 feat: redux 이용한 API 연동
  frontend/redux/modules/districts.js
  frontend/redux/modules/posts.js
  frontend/redux/modules/reducer.js
  frontend/redux/modules/restaurant.js
  frontend/redux/modules/review.js
  frontend/redux/store.js
  frontend/services/auth.service.js
Labels: 📬 API

#73 fix: redux 이용함에 따라 일부 페이지 수정
  frontend/components/common/Footer.jsx
  frontend/components/district/District.jsx
  frontend/components/district/DistrictMap.jsx
  frontend/components/district/containers/DistrictContainers.jsx
  frontend/components/restaurant/Restaurant.jsx
  frontend/components/restaurant/RestaurantMap.jsx
  frontend/components/restaurant/containers/RestaurantContainers.jsx
  frontend/components/user/LoginForm.jsx
  frontend/components/user/RegisterForm.jsx
  frontend/components/user/UserProfile.jsx
  frontend/pages/community.js
  frontend/pages/restaurants/[[...params]].js
  frontend/pages/seoul/[[...params]].js
  frontend/redux/modules/user.js
Labels: 🔨 Refactor, 🎨 Html&css

#74 feat: diet에 채식타입 컬럼 추가
  backend/src/main/java/com/project/vegan/domain/diet/entity/Diet.java
  backend/src/main/java/com/project/vegan/domain/diet/request/DietSaveRequest.java
  backend/src/main/java/com/project/vegan/domain/diet/response/DietDto.java
  backend/src/main/java/com/project/vegan/domain/diet/service/DietService.java
Labels: ✨ Feature

#79 feat: 기본 식단 관련 기능 구현
  frontend/components/common/VegetarianTypes.jsx
  frontend/components/diet/DayDiet.jsx
  frontend/components/diet/Detail.jsx
  frontend/components/diet/Diet.jsx
  frontend/components/diet/DietForm.jsx
  frontend/components/diet/EditForm.jsx
  frontend/components/diet/MoreFeature.jsx
  frontend/components/diet/containers/DietDetailContainer.jsx
  frontend/components/diet/containers/DietsLIstContainer.jsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/detailDiet/[[...params]].js
  frontend/pages/dietPage.js
  frontend/pages/editDiet/[[...params]].js
  frontend/pages/foodRecord.js
  frontend/pages/writeDiet.js
  frontend/services/diet.service.js
  frontend/yarn.lock
Labels: ✨ Feature, 📬 API

#81 feat: 예외 처리 및 권한 처리
  backend/src/main/java/com/project/vegan/domain/diet/controller/DietController.java
  backend/src/main/java/com/project/vegan/domain/like/controller/LikeController.java
  backend/src/main/java/com/project/vegan/domain/member/controller/MemberController.java
  backend/src/main/java/com/project/vegan/domain/post/controller/PostController.java
  backend/src/main/java/com/project/vegan/domain/review/controller/ReviewController.java
  backend/src/main/java/com/project/vegan/global/config/SecurityConfig.java
  backend/src/main/java/com/project/vegan/global/error/GlobalExceptionHandler.java
  backend/src/main/java/com/project/vegan/global/error/dto/ErrorResult.java
Labels: ✨ Feature

#85 feat: 채식피드 api 스펙 변경
  backend/src/main/java/com/project/vegan/domain/like/response/LikePostDto.java
  backend/src/main/java/com/project/vegan/domain/post/controller/PostController.java
  backend/src/main/java/com/project/vegan/domain/post/response/PostDto.java
  backend/src/main/java/com/project/vegan/domain/post/service/PostService.java
  backend/src/main/java/com/project/vegan/global/config/InitDb.java
Labels: ✨ Feature

#86 feat: 리뷰 api 권한 수정
  backend/src/main/java/com/project/vegan/domain/review/controller/ReviewController.java
Labels: ✨ Feature

#87 feat: 식당 리뷰 평점 계산 수정
  backend/src/main/java/com/project/vegan/domain/review/entity/Review.java
  backend/src/main/java/com/project/vegan/domain/store/response/StoreDetailDto.java
  backend/src/main/java/com/project/vegan/domain/store/response/StoreDto.java
  backend/src/main/resources/application-real.yml
  backend/src/main/resources/application.yml
Labels: ✨ Feature

#90 feat: 날짜별 식단 조회 추가
  backend/src/main/java/com/project/vegan/domain/diet/controller/DietController.java
  backend/src/main/java/com/project/vegan/domain/diet/repository/DietRepositoryCustom.java
  backend/src/main/java/com/project/vegan/domain/diet/repository/DietRepositoryImpl.java
  backend/src/main/java/com/project/vegan/domain/diet/service/DietService.java
  backend/src/main/resources/application.yml
Labels: ✨ Feature

#91 fix: 수정
  backend/src/main/java/com/project/vegan/domain/diet/repository/DietRepositoryImpl.java
Labels: ✨ Feature

#92 feat: 식단 기능 캘린더 구현
  frontend/components/calendar/CalendarBtn.jsx
  frontend/components/calendar/CalendarRow.jsx
  frontend/components/calendar/index.jsx
  frontend/pages/foodRecord/calendar/index.js
Labels: ✨ Feature

#96 fix: 비건 피드 관련 수정
  frontend/components/feed/FeedForm.jsx
  frontend/components/feedComponent/CommentForm.jsx
  frontend/components/feedComponent/EditForm.jsx
  frontend/components/feedComponent/FeedForm.jsx
  frontend/components/feedComponent/MoreFeature.jsx
  frontend/components/feedComponent/containers/FeedListContainer.jsx
  frontend/components/feedComponent/containers/ReviewListContainer.jsx
  frontend/components/feedComponent/index.jsx
  frontend/pages/feed/edit/[[...params]].js
  frontend/pages/feed/index.js
  frontend/pages/feed/post.js
  frontend/pages/feedPage.js
  frontend/pages/writeFeed.js
Labels: 🎨 Html&css

#98 fix: 사용자 관련 기능 페이지 및 컴포넌트 수정
  frontend/components/member/EditProfile.jsx
  frontend/components/member/LoginForm.jsx
  frontend/components/member/RegisterForm.jsx
  frontend/components/member/UserProfile.jsx
  frontend/components/user/LoginForm.jsx
  frontend/components/user/RegisterForm.jsx
  frontend/components/user/UserProfile.jsx
  frontend/pages/editProfile.js
  frontend/pages/mypage.js
  frontend/pages/register.js
  frontend/pages/user/login.js
  frontend/pages/user/mypage.js
  frontend/pages/user/register.js
  frontend/reducers/user.js
Labels: 🎨 Html&css

#100 feat: 리뷰 관련 기능 구현 및 수정
  frontend/components/review/Review.jsx
  frontend/components/review/Reviewform.jsx
  frontend/components/reviewComponent/EditForm.jsx
  frontend/components/reviewComponent/MoreFeature.jsx
  frontend/components/reviewComponent/Review.jsx
  frontend/components/reviewComponent/Reviewform.jsx
  frontend/pages/review/[[...params]].js
  frontend/pages/review/edit/[[...params]].js
  frontend/pages/review/post/[[...params]].js
  frontend/pages/writeReview/[[...params]].js
Labels: ✨ Feature, 🎨 Html&css

#102 style: 프로젝트 디자인 및 레이아웃 변경
  frontend/components/common/DistrictTitle.jsx
  frontend/components/common/FormBtn.jsx
  frontend/components/common/MainLayout.jsx
  frontend/components/common/MainMenu.jsx
  frontend/components/common/Nav.jsx
  frontend/components/common/SubMenu.jsx
  frontend/components/intro/Vegetarian.jsx
  frontend/components/intro/index.jsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.js
  frontend/pages/index.js
  frontend/pages/information/[[...params]].js
  frontend/pages/login.js
  frontend/reducers/index.js
  frontend/reducers/post.js
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#106 feat: 채식 식단 기록 관련 차트 구현
  frontend/components/VegeTrend/DietChart.jsx
  frontend/components/VegeTrend/VegeLevel.jsx
  frontend/components/VegeTrend/VegeMonth.jsx
  frontend/components/VegeTrend/VegeType.jsx
  frontend/components/VegeTrend/containers/DietsListContainer.jsx
  frontend/components/VegeTrend/containers/VegeCount.jsx
  frontend/components/VegeTrend/index.jsx
  frontend/components/calendar/CalendarBtn.jsx
  frontend/components/diet/DayDiet.jsx
  frontend/components/diet/Detail.jsx
  frontend/components/diet/DietComponent.jsx
  frontend/components/diet/DietForm.jsx
  frontend/components/diet/DietsAll.jsx
  frontend/components/diet/containers/DietsAllContainer.jsx
  frontend/components/diet/containers/DietsLIstContainer.jsx
  frontend/components/diet/index.jsx
  frontend/components/information/VegeRanking.jsx
  frontend/pages/foodRecord/all.js
  frontend/pages/foodRecord/calendar/index.js
  frontend/pages/foodRecord/detail/[[...params]].js
  frontend/pages/foodRecord/index.js
  frontend/pages/foodRecord/list/[[...params]].js
  frontend/pages/foodRecord/trend.js
  frontend/pages/information/[[...params]].js
Labels: ✨ Feature, 🎨 Html&css, 📬 API
