Repository imssein/VEGIN, pull requests merged in 2022-08, with the labels that each got.

#19 feat: 프로젝트 세팅
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/project/vegan/VeganApplication.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data/data.json
  backend/src/test/java/com/project/vegan/VeganApplicationTests.java
Labels: ✨ Feature

#20 Fix/3
  frontend/components/user/EditProfile.jsx
  frontend/components/user/RegisterForm.jsx
  frontend/components/user/UserProfile.jsx
  frontend/pages/editProfile.js
  frontend/pages/mypage.js
  frontend/services/user.service.js
Labels: 🐞 BugFix

#25 feat: 식당 리뷰/피드 작성 페이지 구현
  frontend/components/common/FormBtn.jsx
  frontend/components/common/UploadImage.jsx
  frontend/components/common/VegitarianTypes.jsx
  frontend/components/post/FeedForm.jsx
  frontend/components/restaurants/RestaurantDetail.jsx
  frontend/components/review/Reviewform.jsx
  frontend/pages/feed/[[...params]].js
  frontend/pages/restaurants/[[...params]].js
  frontend/pages/review/[[...params]].js
  frontend/public/images/lactoovologo.png
Labels: ✨ Feature

#30 feat: 기존 기능 redux 이용하여 구현
  frontend/components/common/Footer.jsx
  frontend/components/common/FormBtn.jsx
  frontend/components/common/UploadImage.jsx
  frontend/components/common/VegetarianTypes.jsx
  frontend/components/common/VegitarianTypes.jsx
  frontend/components/nearbySearch/NearbyRestaurant.jsx
  frontend/components/post/FeedForm.jsx
  frontend/components/post/PostFormLogo.jsx
  frontend/components/user/LoginForm.jsx
  frontend/components/user/UserProfile.jsx
  frontend/pages/community.js
  frontend/pages/feed/[[...params]].js
  frontend/pages/writePost.js
  frontend/reducers/user.js
  frontend/store/configureStore.js
Labels: ✨ Feature

#33 feat: 카카오맵 커스텀 오버레이 구현
  frontend/components/seoulMap/DistrictMap.jsx
  frontend/components/seoulMap/Ex.jsx
Labels: ✨ Feature

#35 fix: 내 위치에 따른 채식 식당 마커 표시
  frontend/components/nearbySearch/GeolocationParams.jsx
  frontend/components/seoulMap/DistrictMap.jsx
  frontend/pages/seoul/[[...params]].js
Labels: 🐞 BugFix

#42 fix: 배포 후 사이트 수정
  frontend/components/common/Nav.jsx
  frontend/components/intro/SearchForm.jsx
  frontend/components/intro/Title.jsx
  frontend/pages/community.js
  frontend/pages/foodRecord.js
  frontend/pages/index.js
  frontend/pages/information.js
  frontend/pages/login.js
  frontend/pages/mypage.js
  frontend/pages/nearbySearch.js
  frontend/pages/register.js
  frontend/pages/writePost.js
  frontend/public/favicon.ico
  frontend/public/images/logo.png
Labels: 🎨 Html&css

#45 feat: 채식 가이드 레이아웃 구현
  frontend/components/common/VegeInfo.jsx
  frontend/components/information/index.jsx
  frontend/components/intro/Menu.jsx
  frontend/components/intro/VeganGuide.jsx
  frontend/components/intro/VegeInfo.jsx
  frontend/components/intro/index.jsx
  frontend/pages/information.js
  frontend/pages/information/[[...params]].js
  frontend/public/images/calender.png
  frontend/public/images/feed.png
  frontend/public/images/restaurant.png
  frontend/public/images/vegeinfo.jpg
Labels: ✨ Feature

#38 feat: 엔티티 생성 및 로그인 기능 구현
  backend/src/main/java/com/project/vegan/domain/common/entity/BaseEntity.java
  backend/src/main/java/com/project/vegan/domain/diet/entity/Diet.java
  backend/src/main/java/com/project/vegan/domain/diet/repository/DietRepository.java
  backend/src/main/java/com/project/vegan/domain/like/entity/Like.java
  backend/src/main/java/com/project/vegan/domain/like/repository/LikeRepository.java
  backend/src/main/java/com/project/vegan/domain/member/controller/MemberController.java
  backend/src/main/java/com/project/vegan/domain/member/entity/Member.java
  backend/src/main/java/com/project/vegan/domain/member/exception/MemberDuplicateException.java
  backend/src/main/java/com/project/vegan/domain/member/exception/MemberNotFoundException.java
  backend/src/main/java/com/project/vegan/domain/member/exception/PasswordMismatchException.java
  backend/src/main/java/com/project/vegan/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/project/vegan/domain/member/request/MemberJoinRequest.java
  backend/src/main/java/com/project/vegan/domain/member/request/MemberLoginRequest.java
  backend/src/main/java/com/project/vegan/domain/member/response/MemberDto.java
  backend/src/main/java/com/project/vegan/domain/member/response/MemberJoinResponse.java
  backend/src/main/java/com/project/vegan/domain/member/response/MemberLoginResponse.java
  backend/src/main/java/com/project/vegan/domain/member/service/MemberService.java
  backend/src/main/java/com/project/vegan/domain/post/entity/Post.java
  backend/src/main/java/com/project/vegan/domain/post/entity/PostUploadFile.java
  backend/src/main/java/com/project/vegan/domain/post/repository/PostRepository.java
  backend/src/main/java/com/project/vegan/domain/review/entity/Review.java
  backend/src/main/java/com/project/vegan/domain/review/entity/ReviewUploadFile.java
  backend/src/main/java/com/project/vegan/domain/review/repository/ReviewRepository.java
  backend/src/main/java/com/project/vegan/domain/store/entity/Category.java
  backend/src/main/java/com/project/vegan/domain/store/entity/District.java
  backend/src/main/java/com/project/vegan/domain/store/entity/Store.java
  backend/src/main/java/com/project/vegan/domain/store/entity/StoreUploadFile.java
  backend/src/main/java/com/project/vegan/domain/store/repository/StoreRepository.java
  backend/src/main/java/com/project/vegan/global/config/EncoderConfig.java
  backend/src/main/java/com/project/vegan/global/config/JpaAuditingConfig.java
  backend/src/main/java/com/project/vegan/global/config/QuerydslConfig.java
  backend/src/main/java/com/project/vegan/global/config/SecurityConfig.java
  backend/src/main/java/com/project/vegan/global/exception/ForbiddenException.java
  backend/src/main/java/com/project/vegan/global/exception/NotFoundException.java
  backend/src/main/java/com/project/vegan/global/jwt/exception/TokenHasExpiredException.java
  backend/src/main/java/com/project/vegan/global/jwt/exception/TokenIsInvalidException.java
  backend/src/main/java/com/project/vegan/global/jwt/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/project/vegan/global/jwt/service/JwtProvider.java
  backend/src/main/java/com/project/vegan/global/security/CustomPrincipalDetailsService.java
  backend/src/main/java/com/project/vegan/global/security/PrincipalDetails.java
  backend/src/main/java/com/project/vegan/global/security/annotation/LoginMember.java
Labels: ✨ Feature

#47 feat: 식당과 사용자 위치 거리 계산
  frontend/components/distance/Address2LatLng.jsx
  frontend/components/distance/Address2Wtm.jsx
  frontend/components/distance/Test.jsx
  frontend/components/searchfilter/DistanceCalculator.jsx
  frontend/components/searchfilter/DistanceLogo.jsx
  frontend/components/searchfilter/DistanceRange.jsx
  frontend/components/searchfilter/LatLng2Wtm.jsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/nearbySearch.js
  frontend/services/store.service.js
  frontend/yarn.lock
Labels: ✨ Feature

#50 fix: 변환 안된 데이터 삽입
  frontend/components/distance/Address2Wtm.jsx
Labels: 🐞 BugFix

#55 fix: 식당 조회 관련 API 받아오는 부분 수정
  frontend/components/restaurants/RestaurantDetail.jsx
  frontend/components/restaurants/RestaurantMap.jsx
  frontend/components/seoulMap/SeoulData.jsx
  frontend/pages/restaurants/[[...params]].js
  frontend/services/store.service.js
Labels: 📬 API

#56 feat: 식당 검색 기능 구현
  frontend/components/nearbySearch/RestaurantsData.jsx
  frontend/components/nearbySearch/RestaurantsList.jsx
  frontend/components/search/GeolocationPrint.jsx
  frontend/components/search/KakaoMap.jsx
  frontend/components/search/SearchData.jsx
  frontend/components/search/SearchMain.jsx
  frontend/components/seoulMap/DistrictMap.jsx
  frontend/components/seoulMap/SeoulData.jsx
  frontend/pages/search.js
Labels: ✨ Feature, 📬 API

#53 feat: 리뷰 api 구현
  backend/src/main/java/com/project/vegan/domain/review/controller/ReviewController.java
  backend/src/main/java/com/project/vegan/domain/review/entity/Review.java
  backend/src/main/java/com/project/vegan/domain/review/repository/ReviewRepositoryCustom.java
  backend/src/main/java/com/project/vegan/domain/review/repository/ReviewRepositoryImpl.java
  backend/src/main/java/com/project/vegan/domain/review/request/ReviewSaveRequest.java
  backend/src/main/java/com/project/vegan/domain/review/response/ReviewSaveResponse.java
  backend/src/main/java/com/project/vegan/domain/review/service/ReviewService.java
  backend/src/main/java/com/project/vegan/domain/store/entity/Store.java
  backend/src/main/java/com/project/vegan/domain/store/service/StoreService.java
Labels: ✨ Feature

#59 feat: 리뷰 수정 추가 및 기타 수정
  backend/src/main/java/com/project/vegan/domain/review/controller/ReviewController.java
  backend/src/main/java/com/project/vegan/domain/review/entity/Review.java
  backend/src/main/java/com/project/vegan/domain/review/service/ReviewService.java
Labels: ✨ Feature

#61 feat: cross origin 추가
  backend/src/main/java/com/project/vegan/domain/post/controller/PostController.java
Labels: ✨ Feature
